### ISSUE TITLE
Use with bootstrap

### ISSUE THREAD

**Issue by XadillaX** [alexwolfe/Buttons#22]
when I use it with bootstrap, and when I use `<a></a>`, the button goes ugly!

Because the `<a>` in bootstrap will override the button while there's no CSS that like `a.button`.

**Comment by wangpingsx** [comment]
Have you fixed bower version?

with the code from your sample : 

<span class="button-wrap"><a href="#" class="buttonccc buttonccc-circle buttonccc-primary">press me</a></span>

I got this:

![image](https://cloud.githubusercontent.com/assets/1758819/6770135/e9a9c456-d0ae-11e4-9fa2-775a659540bc.png)

Thanks,
Peter

**Comment by alexwolfe** [comment]
Are you using the latest version: http://unicorn-ui.com/buttons/
