### ISSUE TITLE
Autoprefixer: Gradient has outdated direction syntax. New syntax is like "to left" instead of "right".

### ISSUE THREAD

**Issue by kevinxh** [alexwolfe/Buttons#73]
I was trying to compile the sass files with gulp-autoprefixer.

However the autoprefixer shows error:

**"Gradient has outdated direction syntax. New syntax is like "to left" instead of "right"."**

_$ubtn-use-compass is set to false_

**Comment by PokimLee** [comment]
same problem too, hope to update the css new syntax

**Comment by alexwolfe** [comment]
@kevinxh You wanna take a crack at fixing this one and I'll merge it in?
